<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>sobits_intball2_gnc</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="rg-msi-01@todo.todo">rg-msi-01</maintainer>
  <license>TODO: License declaration</license>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>nav_msgs</depend>
  <depend>trajectory_msgs</depend>
  <depend>ib2_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>python3-yaml</depend>
  <depend>python3-numpy</depend>
  <depend>python3-scipy</depend>
  <depend>ament_index_python</depend>
  <depend>minco_native_py</depend>

  <exec_depend>ros2launch</exec_depend>
  <exec_depend>intball2_programs</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
